function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "ArrayOperations"};
	this.sidHashMap["ArrayOperations"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "ArrayOperations:7"};
	this.sidHashMap["ArrayOperations:7"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<Root>/Input"] = {sid: "ArrayOperations:22"};
	this.sidHashMap["ArrayOperations:22"] = {rtwname: "<Root>/Input"};
	this.rtwnameHashMap["<Root>/Divide"] = {sid: "ArrayOperations:15"};
	this.sidHashMap["ArrayOperations:15"] = {rtwname: "<Root>/Divide"};
	this.rtwnameHashMap["<Root>/From"] = {sid: "ArrayOperations:8"};
	this.sidHashMap["ArrayOperations:8"] = {rtwname: "<Root>/From"};
	this.rtwnameHashMap["<Root>/From1"] = {sid: "ArrayOperations:9"};
	this.sidHashMap["ArrayOperations:9"] = {rtwname: "<Root>/From1"};
	this.rtwnameHashMap["<Root>/From2"] = {sid: "ArrayOperations:10"};
	this.sidHashMap["ArrayOperations:10"] = {rtwname: "<Root>/From2"};
	this.rtwnameHashMap["<Root>/From3"] = {sid: "ArrayOperations:17"};
	this.sidHashMap["ArrayOperations:17"] = {rtwname: "<Root>/From3"};
	this.rtwnameHashMap["<Root>/Goto"] = {sid: "ArrayOperations:2"};
	this.sidHashMap["ArrayOperations:2"] = {rtwname: "<Root>/Goto"};
	this.rtwnameHashMap["<Root>/MATLAB Function"] = {sid: "ArrayOperations:7"};
	this.sidHashMap["ArrayOperations:7"] = {rtwname: "<Root>/MATLAB Function"};
	this.rtwnameHashMap["<Root>/Max"] = {sid: "ArrayOperations:3"};
	this.sidHashMap["ArrayOperations:3"] = {rtwname: "<Root>/Max"};
	this.rtwnameHashMap["<Root>/Max1"] = {sid: "ArrayOperations:5"};
	this.sidHashMap["ArrayOperations:5"] = {rtwname: "<Root>/Max1"};
	this.rtwnameHashMap["<Root>/Sum of Elements"] = {sid: "ArrayOperations:6"};
	this.sidHashMap["ArrayOperations:6"] = {rtwname: "<Root>/Sum of Elements"};
	this.rtwnameHashMap["<Root>/Output"] = {sid: "ArrayOperations:18"};
	this.sidHashMap["ArrayOperations:18"] = {rtwname: "<Root>/Output"};
	this.rtwnameHashMap["<Root>/Output1"] = {sid: "ArrayOperations:19"};
	this.sidHashMap["ArrayOperations:19"] = {rtwname: "<Root>/Output1"};
	this.rtwnameHashMap["<Root>/Output2"] = {sid: "ArrayOperations:20"};
	this.sidHashMap["ArrayOperations:20"] = {rtwname: "<Root>/Output2"};
	this.rtwnameHashMap["<Root>/Output3"] = {sid: "ArrayOperations:21"};
	this.sidHashMap["ArrayOperations:21"] = {rtwname: "<Root>/Output3"};
	this.rtwnameHashMap["<S1>:1"] = {sid: "ArrayOperations:7:1"};
	this.sidHashMap["ArrayOperations:7:1"] = {rtwname: "<S1>:1"};
	this.rtwnameHashMap["<S1>:1:3"] = {sid: "ArrayOperations:7:1:3"};
	this.sidHashMap["ArrayOperations:7:1:3"] = {rtwname: "<S1>:1:3"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
